CREATE TABLE ledger (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    inspection_type VARCHAR(255) NOT NULL COMMENT '巡查类型',
    check_time DATE NOT NULL COMMENT '排查时间',
    rectification_deadline DATE COMMENT '限期整改时间',
    hazard_severity VARCHAR(50) COMMENT '隐患严重程度',
    issue_category VARCHAR(255) COMMENT '问题大类',
    sub_category VARCHAR(255) COMMENT '问题子类',
    detailed_category VARCHAR(255) COMMENT '详细分类',
    department VARCHAR(255) COMMENT '责任科室',
    hazard_area VARCHAR(255) COMMENT '隐患区域',
    person_in_charge VARCHAR(255) COMMENT '责任人',
    sub_area VARCHAR(255) COMMENT '子区域',
    detailed_area VARCHAR(255) COMMENT '详细区域',
    issue_object VARCHAR(255) COMMENT '问题对象',
    issue_mode VARCHAR(255) COMMENT '问题模式',
    l_value DOUBLE COMMENT 'L值',
    e_value DOUBLE COMMENT 'E值',
    c_value DOUBLE COMMENT 'C值',
    d_value DOUBLE COMMENT 'D值',
    before_rectification_photo VARCHAR(500) COMMENT '整改前照片',
    issue_description TEXT COMMENT '问题描述',
    is_first_discovery BOOLEAN DEFAULT FALSE COMMENT '是否首次发现',
    team_leader VARCHAR(255) COMMENT '区域班组长',
    deduction_score DOUBLE COMMENT '扣分值',
    inspector VARCHAR(255) COMMENT '检查人',
    after_rectification_photo VARCHAR(500) COMMENT '整改后照片',
    analysis_and_measures TEXT COMMENT '原因分析及整改措施',
    rectification_finish_time DATE COMMENT '整改完成时间',
    assessment_person VARCHAR(255) COMMENT '考核人员',
    assessment_amount DOUBLE COMMENT '考核金额',
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间'
) COMMENT='燃气动力公司安全生产隐患排查治理台账表';
