CREATE TABLE safety_ledger (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    inspection_type VARCHAR(255),
    check_time DATE,
    rectification_deadline DATE,
    hazard_severity VARCHAR(255),
    issue_category VARCHAR(255),
    sub_category VARCHAR(255),
    detailed_category VARCHAR(255),
    department VARCHAR(255),
    hazard_area VARCHAR(255),
    person_in_charge VARCHAR(255),
    sub_area VARCHAR(255),
    detailed_area VARCHAR(255),
    issue_object VARCHAR(255),
    issue_mode VARCHAR(255),
    l_value INT,
    e_value INT,
    c_value INT,
    d_value INT,
    before_rectification_photos TEXT,
    issue_description TEXT,
    is_first_discovery BOOLEAN,
    team_leader VARCHAR(255),
    deduction_score DECIMAL(10,2),
    inspector VARCHAR(255),
    after_rectification_photos TEXT,
    analysis_and_measures TEXT,
    rectification_finish_time DATE,
    assessment_person VARCHAR(255)
);
